archives:
- id: zip
  format: zip
- id: txz
  format: txz

brews:
- repository:
    owner: xmit-co
    name: homebrew-tap
    branch: main
  description: 'Launch static websites on xmit.co'
  homepage: https://xmit.co/
