archives:
- id: zip
  format: zip
  wrap_in_directory: true
- id: txz
  format: txz
  wrap_in_directory: true
- id: tgz
  format: tgz
  wrap_in_directory: true

brews:
- repository:
    owner: xmit-co
    name: homebrew-tap
  description: 'Launch static websites on xmit.co'
  homepage: https://xmit.co/
